version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: yarn run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
